services:
  server:
    build:
      context: ../../..
      dockerfile: ./docker/Dockerfile/Dockerfile.server
    container_name: server-cpp
    environment:
      - PROTOCOL=plain
      - HOST_TCPDUMP_LISTEN_PORT=9876
      - SSLKEYLOGFILE=/logs/sslkey.log
    volumes:
      - ../../../tests/logs:/logs
    networks:
      - inner-default

  client1:
    build:
      context: ../../..
      dockerfile_inline: |
        FROM alpine:latest
        # install cmake
        RUN apk update && apk upgrade
        RUN apk add --no-cache make cmake g++ mbedtls-static mbedtls-dev
        WORKDIR /cpp-mqttmtd-cli/build
        RUN echo "mkdir /cpp-mqttmtd-cli/build; cd /cpp-mqttmtd-cli/build || return; cmake ..; make;" > /run_cmake.sh
        # add user
        ARG CLIENT_UID=1001
        ARG CLIENT_NAME=client1
        RUN adduser -u $${CLIENT_UID} -D $${CLIENT_NAME}
        USER $${CLIENT_NAME}
        ENTRYPOINT ["/bin/sh"]
    container_name: client1-cpp
    environment:
      - CLIENT_NAME=client1
    networks:
      - inner-default
    volumes:
      - "../../../cpp-mqttmtd-cli:/cpp-mqttmtd-cli"
      - "../../../tests/certs/ca/ca.crt:/certs/ca/ca.crt"
      - "../../../tests/certs/clients:/certs/clients"
      - "../../../tests/mqttmtd/conf:/mqttmtd/conf"
      - "../../../tests/mosquitto/conf:/mosquitto/conf"
    tty: true
    stdin_open: true
    init: true
    stop_grace_period: 2s

networks:
  inner-default: