[package]
name = "mqttmtd-authserver"
version = "2.0.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
libmqttmtd = { path = "../libmqttmtd" }
ring = "0.17.14"
rustls = "0.23.26"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.44.2", features = ["io-util"] }
tokio-rustls = { version = "0.26.2", features = ["ring"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.14", features = ["full"] }

[dev-dependencies]
tempfile = "3.19.1"
