services:
  # Broker
  broker:
    build:
      context: ./broker
    image: mqtt-mtd/hopper-label/broker
    privileged: true
    volumes:
      - ./go:/mosquitto/go:ro
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ../certs/broker:/mosquitto/config/certs/broker:ro
      - ../certs/ca:/mosquitto/config/certs/ca:ro
    hostname: broker
    tty: true
    stdin_open: true
    restart: always
    networks:
      - net

  # Publisher
  pub:
    build:
      context: ./client
    image: mqtt-mtd/hopper-label/client
    volumes:
      - ./go:/mosquitto/go:ro
      - ../certs/client:/mosquitto/config/certs/client:ro
      - ../certs/ca:/mosquitto/config/certs/ca:ro
    hostname: publisher
    tty: true
    networks:
      - net

  # Subscriber
  sub:
    build:
      context: ./client
    image: mqtt-mtd/hopper-label/client
    volumes:
      - ./go:/mosquitto/go:ro
      - ../certs/client:/mosquitto/config/certs/client:ro
      - ../certs/ca:/mosquitto/config/certs/ca:ro
    hostname: subscriber
    tty: true
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
