[package]
name = "libmqttmtd"
version = "2.0.0"
edition = "2024"

[dev-dependencies]
tempfile = "3"

[dependencies]
bytes = "1.10.1"
rcgen = "0.13.2"
ring = "0.17.14"
rustls = { version = "0.23.26", features = ["std", "ring"] }
rustls-pemfile = "2.2.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-rustls = "0.26.2"
