services:
  # Broker
  broker:
    build:
      context: ./broker
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs/broker:/mosquitto/config/certs/broker
      - ./certs/ca:/mosquitto/config/certs/ca
    hostname: broker
    tty: true
    stdin_open: true
    ports:
      - "8883:8883"
    restart: always
    networks:
      - net

  # Publisher
  pub:
    build:
      context: ../../mosquitto-cli
    volumes:
      - ./certs/client:/mosquitto/config/certs/client
      - ./certs/ca:/mosquitto/config/certs/ca
    hostname: publisher
    tty: true
    networks:
      - net

  # Subscriber
  sub:
    build:
      context: ../../mosquitto-cli
    volumes:
      - ./certs/client:/mosquitto/config/certs/client
      - ./certs/ca:/mosquitto/config/certs/ca
    tty: true
    network_mode: "service:broker"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
