services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfiles/Dockerfile.server
    container_name: server
    environment:
      - PROTOCOL=${PROTOCOL}
    networks:
      - inner-default

  client1:
    build:
      context: ..
      dockerfile: ./docker/Dockerfiles/Dockerfile.client_wrapper
    container_name: client1
    environment:
      - PROTOCOL=${PROTOCOL}
      - CLIENT_NAME="client1"
      - INTEGRATION_TESTS_CONF=/mqttmtd/conf/testing.toml
    networks:
      - inner-default
    volumes:
      - "../rust-mqttmtd:/rust-mqttmtd"
      - "../tests/certs/ca/ca.crt:/certs/ca/ca.crt"
      - "../tests/certs/clients:/certs/clients"
      - "../tests/mqttmtd/conf:/mqttmtd/conf"
      - "../tests/mosquitto/conf:/mosquitto/conf"
      - "../tests/scripts:/scripts"
    tty: true
    stdin_open: true

networks:
  inner-default: