services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.server
    container_name: server
    environment:
      - PROTOCOL=wss
  client:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.client