FROM golang:1.22.5-alpine3.20
WORKDIR /mqttmtd/go/tokenmgr/tests
COPY ./go/ /mqttmtd/go/

COPY ./certs/ca /mqttmtd/certs/ca

ARG CLIENT_NAME
COPY certs/clients/$CLIENT_NAME.crt /mqttmtd/certs/client/$CLIENT_NAME.crt
COPY certs/clients/$CLIENT_NAME.key /mqttmtd/certs/client/$CLIENT_NAME.key
