services:
  server:
    build:
      context: ../../..
      dockerfile: ./docker/Dockerfile/Dockerfile.server
    container_name: server
    environment:
      - PROTOCOL=plain
      - HOST_TCPDUMP_LISTEN_PORT=9876
      - SSLKEYLOGFILE=/logs/sslkey.log
    volumes:
      - ../../../tests/logs:/logs
    networks:
      - inner-default

  client1:
    build:
      context: ../../..
      dockerfile_inline: |
        FROM rust:1.86-alpine
        # install mosquitto & musl
        RUN apk update && apk upgrade
        RUN apk add --no-cache mosquitto-clients musl-dev gcc
        # add user
        ARG CLIENT_UID=1001
        ARG CLIENT_NAME=client1
        RUN adduser -u $${CLIENT_UID} -D $${CLIENT_NAME}
        USER $${CLIENT_NAME}
        WORKDIR /rust-mqttmtd/tokenmgr
    container_name: client1
    environment:
      - CLIENT_NAME=client1
      - INTEGRATION_TESTS_CONF=/mqttmtd/conf/testing.toml
    networks:
      - inner-default
    volumes:
      - "../../../rust-mqttmtd:/rust-mqttmtd"
      - "../../../tests/certs/ca/ca.crt:/certs/ca/ca.crt"
      - "../../../tests/certs/clients:/certs/clients"
      - "../../../tests/mqttmtd/conf:/mqttmtd/conf"
      - "../../../tests/mosquitto/conf:/mosquitto/conf"
    tty: true
    stdin_open: true
    init: true
    stop_grace_period: 2s

networks:
  inner-default: